{{- if .Values.developmentSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "main-chart.fullname" . }}
  labels:
    {{- include "main-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.developmentSecret.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end }}