apiVersion: v1
kind: Namespace
metadata:
  name: liferay
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
  namespace: liferay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - image: mariadb:11.1.2
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test"
        - name: MYSQL_DATABASE
          value: "test"
        - name: MYSQL_USER
          value: "test"
        - name: MYSQL_PASSWORD
          value: "test"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: liferay
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: database
