name: GitOps deployment
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Set Short Sha Variable
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build
        run: docker build -t "liferay:${{ steps.vars.outputs.sha_short }}" .

      - name: Docker Hub Login
        run: docker login -u viniciuslsdias -p $DOCKER_HUB_TOKEN

      - name: Push Docker Image
        run: docker push "viniciuslsdias/liferay:${{ steps.vars.outputs.sha_short }}"